services:
  api:
  image: ghcr.io/johngalarza/demo-cicd-api:latest
  container_name: demo-cicd-api
  ports:
    - "8080:8080"
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - GIT_SHA=local
